# Copyright 2017 Vinnie Falco
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

sudo: false

language: cpp

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest

notifications:
  email:
    on_success: never
